version: '3'
services:
  swagger:
    image: swaggerapi/swagger-ui:v3.23.1
    ports:
      - '8080:8080'
    environment:
      API_URL: 'sandbox/openapi.yaml'
    volumes:
      - .:/usr/share/nginx/html/sandbox
